### ISSUE TITLE
Jestr causes long UI freezes

### ISSUE THREAD

**Issue by dcelasun** [mozilla/jestr-pioneer-shield-study#12]
Apologies if I'm opening this in the wrong place, this was the only relevant link I found searching for "jestr firefox".

Jestr got installed on my Firefox automatically as I'm opted in to all studies/telemetry etc. The problem is it's causing very frequent and long UI freezes, anywhere from 500ms to 2000ms. This started a day or two ago (not sure when) and disabling Jestr resolves the issue immediately, and enabling it brings it back.

This is on Firefox 63.0.3 on Linux.

**Comment by motin** [comment]
Thanks @dcelasun for you report - you have indeed come to the right place! Apologies for the UI freezes. We identified performance issues for some study participants and immediately cancelled the study until further notice. Disabling JESTr (if it has not already been done automatically) is the right thing to do at this point.

The performance issues will be addressed before continuing the study, and updates will be posted in this issue.

Again, thank you for taking the time to report this!

**Comment by dcelasun** [comment]
Thanks @motin for the speedy response!

> Disabling JESTr (if it has not already been done automatically) is the right thing to do at this point.

It wasn't done automatically, but not really a problem for me.

**Comment by mlopatka** [comment]
@dcelasun Thanks again for flagging this issue and for your patience. 
as @motin mentioned, you should have been unenrolled when we backed out this version of JESTr.

If you are still having problems with the lingering study addon, it should be possible to remove it manually at about:studies and/or about:addons. 

In the worst case, you can remove the Firefox Pioneer addon via about:addons, and then restart Firefox. This should unenroll you from all Pioneer studies. 

You may then reinstall the pioneer study addon from here: https://addons.mozilla.org/en-US/firefox/addon/firefox-pioneer/

Thanks again for your feedback and THANK YOU for being a Firefox Pioneer and helping make Firefox better.

**Comment by dcelasun** [comment]
No worries, I've just disabled (not removed) it from about:addons. I didn't want to do more (like removing Pioneer) as I don't want to accidentally disable telemetry or opt out of studies.

Thank *you* folks for making Firefox better.

**Comment by motin** [comment]
This was resolved in v1.1.0. Thanks again for the report!
