### ISSUE TITLE
A succession of errors are displayed in the Browser's Console when having a Private Window opened and the Normal Window is closed

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/jestr-pioneer-shield-study#18]
**[Affected versions]:**
- Firefox Unbranded 67.0.2

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- Have the following prefs set in "about:config" page:
    - shieldStudy.logLevel to info;
	- extensions.legacy.enabled to true;
	- xpinstall.signatures.required to false.
- Have the "Firefox Pioneer" add-on installed through "about:addons" page (https://addons.mozilla.org/en-US/firefox/addon/firefox-pioneer/)
- Have the latest "jestr_pioneer_shield_study-1.2.0" zipped add-on installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open a new Private Window and close the Normal Window.
3. Open the Browser's Console.
4. Navigate to a website and observe the Browser's Console.

**[Expected result]:**
- No errors are displayed.

**[Actual result]:**
- Multiple errors are displayed.

**[Notes]:**
- No telemetry pings are sent in "about:telemetry" page while the Private Window is opened, but there are a few logs (payloads) that are still sent in browser console. Is this intended?
- Attached is a screen recording of the issue:
![error](https://user-images.githubusercontent.com/40061643/59699875-f9c80e80-91fa-11e9-96da-e27113051b1a.gif)

**Comment by motin** [comment]
Thanks, this is due to [a bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1560025). Workaround implemented in https://github.com/mozilla/jestr-pioneer-shield-study/commit/cca7f545d88167482ccc9357fef05df609c20d61

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest (jestr_pioneer_shield_study-1.2.1) zipped add-on installed.
Tested on Windows 10 x64, Mac 10.14 and Arch Linux 4.16.6 x64.

I will verify this issue once more when the "jestr_pioneer_shield_study-1.2.1" add-on will be signed for testing.
