### ISSUE TITLE
The add-on is wrongly displayed on the "about:addons" page

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/jestr-pioneer-shield-study#19]
**[Affected versions]:**
- Firefox Unbranded 67.0.2

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a new Firefox profile created.
- Have the following pref created in "about:config" page:
    - xpinstall.signatures.dev-root to true
- Have the "Firefox Pioneer" add-on installed through "about:addons" page (https://addons.mozilla.org/en-US/firefox/addon/firefox-pioneer/)
- Have the latest "jestr_pioneer_shield_study-1.2.0" signed add-on downloaded.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "about:addons" page on the "Extensions" section.
3. Drag and drop the "jestr_pioneer_shield_study-1.2.0" signed add-on from preconditions.
4. Select  the "Add" and "Ok"  buttons for the prompts displayed.
5. Refresh the page and observe if the add-on is still displayed.

**[Expected result]:**
- The add-on in no longer displayed.

**[Actual result]:**
- The add-on is still displayed.

**[Notes]:**
- Attached is a screen recording of the issue:
![aboutaddons](https://user-images.githubusercontent.com/40061643/59771765-132c9180-92b3-11e9-9a92-a6504ade62cc.gif)

**Comment by motin** [comment]
This was fixed in [v1.2.1](https://github.com/mozilla/jestr-pioneer-shield-study/releases/tag/1.2.1), please re-test and see if this can be closed.

**Comment by Softvision-RemusDranca** [comment]
I have verified this issue and it's no longer reproducible with the latest (jestr_pioneer_shield_study-1.2.2) signed add-on installed.
Tested on Windows 10 x64, Mac 10.14 and Arch Linux 4.16.6 x64.
I will close this issue as verified-fixed.
