### ISSUE TITLE
No payloads are submitted after mid-study slumber stop, only after the browser is restarted

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/jestr-pioneer-shield-study#20]
[Notes]:
- After mid-study slumber stop if the browser is restarted the "Scheduling study expiration in x days" and "We are back after the slumber, simply activate the study and wait for study to expire" logs are sent in browser console and only then the payloads are correctly submitted and telemetry pings are sent in "about:telemetry" page.

[Affected Versions]:
- JESTr Pioneer Shield Study 1.2.0

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Prerequisites]
- Have the latest Firefox 67 unbranded build installed.
- Have the Firefox Pioneer Add-on installed.
- Have the "shieldStudy.logLevel" string pref created with "info" value.
- Have the "xpinstall.signatures.dev-root" boolean pref created with the "true" value.
- Have the JESTr Pioneer Shield Study 1.2.0 signed xpi installed.
- The browser is closed.

[Steps to reproduce]:
1. Set the system date in the future to be a few minutes before reaching 14 days period.
2. Open the Firefox browser.
3. Wait until scheduling mid-study slumber to stop and observe the browser console.
4. Navigate to a few websites from ALEXA and verify if the telemetry pings sent in "about:telemetry".

[Expected results]:
Step 3. The "Mid-study slumber stop" log is displayed in browser console.
Step 4: Telemetry pings are sent in "about:telemetry" page related to the study. 

[Actual results]:
Step 3: The "Mid-study slumber stop" log is displayed in browser console.
Step 4: No telemetry pings are sent.

[Additional Notes]:
- On browser console only the following logs are displayed after mid-study slumber stop:
	- Processing 0 study payloads to batch and send grouped by navigation api.js:12704
	- Sending the 0 navigation batches that are old enough
- Attached a screen recording with the issue:
![mid-study slumber stop](https://user-images.githubusercontent.com/19226534/59773505-648a5000-92b6-11e9-97b3-aaf4e6ee5f9e.gif)

**Comment by motin** [comment]
An attempt to fix this has been included in [v1.2.2](https://github.com/mozilla/jestr-pioneer-shield-study/releases/tag/1.2.2), please re-test with that version of the study add-on.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue and it's no longer reproducible with the latest (jestr_pioneer_shield_study-1.2.2) signed add-on installed.
Tested on Windows 10 x64, Mac 10.14 and Arch Linux 4.16.6 x64.
Considering this, I will close this issue as verified-fixed.
