### ISSUE TITLE
The JESTr Pioneer Shield Study add-on is not uninstalled after the permanent Private Browsing mode is enabled

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/jestr-pioneer-shield-study#21]
[Notes]:
- After permanent Private Browsing is enabled no telemetry are sent in "about:telemetry" but the study remains installed and logs are displayed in browser console.

[Affected Versions]:
- JESTr Pioneer Shield Study 1.2.0

[Affected Platforms]
- All Windows
- All Mac
- All Linux

[Prerequisites]
- Have the latest Firefox 67 unbranded build installed.
- Have the Firefox Pioneer Add-on installed.
- Have the "shieldStudy.logLevel" string pref created with "info" value.
- Have the "xpinstall.signatures.dev-root" boolean pref created with the "true" value.
- Have the JESTr Pioneer Shield Study 1.2.0 signed xpi installed.
- The browser console is opened.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to "about:preferences#privacy" page.
3. Set the "Never remember history" option from the "History" section.
4. From the displayed prompt click the "Restart Firefox now" button.
5. Navigate to "about:support" page and observe the "Extensions" section.
6. Verify if any telemetry pings are sent in "about:telemetry".

[Expected results]:
Step 5: The JESTr Pioneer Shield Study add-on is uninstalled and it is not displayed in "Extensions" section.
Step 6: The unenrolled telemetry are sent.

[Actual results]:
Step 5: The JESTr Pioneer Shield Study add-on is not uninstalled and it is displayed in "Extensions" section.
Step 6: No telemetry pings are sent.

[Additional Notes]:
- Attached a [screen recording with the issue](https://drive.google.com/open?id=1o-5kb4ExLJ1Mpet1nmiBgxKcmuqR1OwZ).

**Comment by motin** [comment]
An attempt to fix this has been included in [v1.2.2](https://github.com/mozilla/jestr-pioneer-shield-study/releases/tag/1.2.2), please re-test with that version of the study add-on (it is somewhat tricky to test these restart conditions with a test-signed study add-on and a production-signed pioneer opt-in add-on, so I haven't been able to confirm the fix on short notice).

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue and it is still reproducible with the latest (jestr_pioneer_shield_study-1.2.2) signed add-on installed.
After forced Private Browsing mode is enabled, the following logs are displayed in browser console after browser restart, but the JESTr Pioneer Shield Study remains installed:
![private](https://user-images.githubusercontent.com/19226534/59845799-e6d24d00-9366-11e9-991b-a51ed2873563.png)


It seems that these logs are displayed after each Firefox restart. Also, no telemetry pings related to the study are sent in "about:telemetry" page. Tested on Windows 7 x64, Windows 10 x64, Mac 10.14 and Arch Linux 4.16.6 x64.
@motin based on the “ending study” logs displayed in browser console, shouldn't the add-on be automatically uninstalled and the specific ending telemetry pings be recorded in "about:telemetry" page?

**Comment by motin** [comment]
This has finally been fixed in [v1.2.3](https://github.com/mozilla/jestr-pioneer-shield-study/releases/tag/1.2.3), please re-test with that version of the study add-on.

**Comment by SoftVision-CosminMuntean** [comment]
I have verified this issue and it's no longer reproducible with the latest (jestr_pioneer_shield_study-1.2.3) signed add-on installed. The study add-on is successfully uninstalled and two encrypted pings are registered in "about:telemetry" page.
Tested on Windows 10 x64, Mac 10.14 and Arch Linux 4.16.6 x64.

Considering this, I will close this issue as verified-fixed.
