### ISSUE TITLE
TypeError: browser.study is undefined; can't access its "onEndStudy" property

### ISSUE THREAD

**Issue by pdehaan** [mozilla/jestr-pioneer-shield-study#6]
Built the study locally, installed Pioneer, then jestr, and spotted this in the Browser Console (using Firefox Nightly):

> TypeError: browser.study is undefined; can't access its "onEndStudy" property . (background.js:49:5)

https://github.com/motin/jestr-pioneer-shield-study/blob/7ddd0ac1a4c09a285c26c4cfa58db8dbed69adb5/src/background.js#L49

<img width="1146" alt="browser_console_and_firefox_nightly_and_issues_ _motin_jestr-pioneer-shield-study_ _github" src="https://user-images.githubusercontent.com/557895/48361695-e3e7df00-e656-11e8-9c33-a1c8ee1b064f.png">

**Comment by motin** [comment]
For unsigned add-ons, make sure to have [`extensions.legacy.enabled` set to true](https://github.com/motin/jestr-pioneer-shield-study/blob/develop/docs/TESTPLAN.md#install-the-add-on-and-enroll-in-the-study) before installing. 

Created issue https://github.com/mozilla/shield-studies-addon-template/issues/89 to make this clearer in the future.
